### ISSUE TITLE
The following modules are missing or built with a differente engine

### ISSUE THREAD

**Issue by vozer** [NegInfinity/ProjectExodus#21] opened 2020-02-12 11:56 UTC
Thx for the plugin!

When i enable the plugin in a blank project in unreal engine 4.24.2 and restart it wants to rebuilld the plugin, but fails to do so.

"The following modules are missing or built with a differente engine" Exodus import. Would you like to rebuild them now?"

"Porject could no be compiled. Try rebuilding from source manually."

In version 2.23.1 he is at least "starting to build" but also failing after a few moments with the same message.

**Comment by NegInfinity** [comment] 2020-02-13 12:56
Hi. Could you provide details? I are cloning from master branch? Are there build errors? I'll check this shortly.

**Comment by vozer** [comment] 2020-02-13 13:55
Hi!
I downloaded (cloned) the repo master branch yes.
I had the same problem now with another project, but it got fixed by installing .net framework and visual studio for game development workload.

But for Exodus it still doesnt work.
When i am home i will try to add an empty c++ class to my blank project and try to build it again with visual studio via the .unrealproject context menu to see if that changes something.

i will keep you updated.

**Comment by NegInfinity** [comment] 2020-02-13 14:45
I've been stuck on trying to implement some feature on wip branch which is not here, and that included some tweaks to get it compile on 4.24 specifically. I'll see if I failed to provide them for the master.

**Comment by Rombond** [comment] 2020-02-18 20:01
Same problem here, is there any solution ?

**Comment by NegInfinity** [comment] 2020-02-18 23:42
@Rombond Given that this is a show stopper, check it in 48 hours to see if I uploaded a fix.

**Comment by NegInfinity** [comment] 2020-02-20 15:22
@Rombond , @vozer I've uploaded an update, see if this fixes the problem. 4.24 deprecated few things, seems that along the way they escalated from warnings to full errors.

**Comment by Rombond** [comment] 2020-02-20 17:35
Same error, i'm on 4.24.1

**Comment by Rombond** [comment] 2020-02-20 17:38
"The following modules are missing or built with a differente engine" Exodus import. Would you like to rebuild them now?"

"Project could not be compiled. Try rebuilding from source manually."

**Comment by NegInfinity** [comment] 2020-02-20 18:11
@Rombond I'm on windows system.

When you compile project on windows, there's a "show log" button which allows you to check the output.

If Mac OS version has similar, could you press the button and copy-paste the output here? This way at least I'll be able to check what the problem is.

**Comment by Rombond** [comment] 2020-02-20 18:24
https://imgur.com/a/2dC6EIL

that is what i have just before "Project could not be compiled. Try rebuilding from source manually."

**Comment by NegInfinity** [comment] 2020-02-20 21:56
@Rombond I need output from the moment AFTER the project fails to compile. Then it will have some sort of output. In the image you posted there are no error messages.

**Comment by Rombond** [comment] 2020-02-20 22:32
I know there is no error on my image,
i made a video on when i have an error https://imgur.com/a/NdYb7mB

There is no log with "Exodus" inside ...

**Comment by NegInfinity** [comment] 2020-02-21 04:59
@Rombond What happens when you try to compile project manually, like the error message suggest?

**Comment by Rombond** [comment] 2020-02-21 05:50
i can't open the project when ExodusImport is activate, i have to delete it manually

**Comment by NegInfinity** [comment] 2020-02-21 06:19
@Rombond  Compiling manually means compiling it through C++ IDE. Without opening UNreal Engine. On Windows it would be compiling through Visual Studio, and on Mac Os that would likely be compiling through XCode. On windows system solution file can be generated by right clicking on *.upgroject and selecting "Generate Visual Studio Project files". Mac OS should have something similar.

**Comment by vozer** [comment] 2020-02-21 11:16
Hey!

So i now did the following:

Installed UE 4.24.2
Installed Visual Studio 2019
Added a Player-C++-Class in the Project

I tried starting it with Exodus Import in Plugins->Exodus Import,. no luck, still the same message.
I compiled the Project manually with Right-Click->Compile, no errors shown but when is tart the project still the same error.

I then opened the Project in Visual Studio and tried to run it and got the following error messages sry, thats in spansih

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'ModuleManager.h': No such file or directory	MyProject	C:\Users\User\Documents\Unreal Projects\MyProject\Plugins\ExodusImport\Source\ExodusImport\Public\JsonImport.h	5	
Error	MSB3075	The command ""C:\Program Files\Epic Games\UE_4.24\Engine\Build\BatchFiles\Build.bat" MyProjectEditor Win64 Development -Project="C:\Users\User\Documents\Unreal Projects\MyProject\MyProject.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.	MyProject	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets	44	
`

https://imgur.com/rkHJHa6
https://imgur.com/744BJLC
https://imgur.com/QlpML9x

**Comment by NegInfinity** [comment] 2020-02-21 14:31
@vozer Okay, this is interesting. I'll try to replicate the issue on my end (because in my case this doesn't happen)

**Comment by NegInfinity** [comment] 2020-02-29 12:44
@vozer, @Rombond  Try the latest version from master and see if that fixes it.

**Comment by Neogene** [comment] 2020-03-10 07:05
In my case the problem was due to the fact I created a Blueprint project and tried to use the plugin, instead using a C++ project worked flawlessly! 

The "only drawback" seems that there is no way to remove the plugin and keeping the material used which is complex to replicate, and removing the plugins folder breaks all the materials created. There should be a way to decouple the. plugin from the material allowing to removing the plugin when is not needed any more but keeping the materials generated (eg: cloning the material from the plugin folder to the import folder generated by the plugin).

**Comment by vozer** [comment] 2020-03-10 07:22
In my case that cant be the problem bc i have a C++ Project. 
But my USB with the Project on it unfortunateley died unexpectedly. 
As soon as i recovered the data i will give you an update.

Thank you!

**Comment by NegInfinity** [comment] 2020-03-10 11:23
@Neogene I think you might be able to duplicate from plugin resources folder (after making it visible), but  easier decoupling is going to be a very low priority, and won't be implemented in near future. 

@vozer There were few issues with include paths, and at some point include path became pedantic.  I fixed it and it should function now. If it doesn't, post an update here.

**Comment by MarshalScorpion** [comment] 2020-12-29 15:07
Hello
I have the same problem. when I try to compile from the source this is the error i get from visual studio:


1>------ Build started: Project: MyProject2, Configuration: Development_Editor x64 ------
1>Parsing headers for MyProject2Editor
1>  Running UnrealHeaderTool "D:\unreal projects\New folder\MyProject2\MyProject2.uproject" "D:\unreal projects\New folder\MyProject2\Intermediate\Build\Win64\MyProject2Editor\Development\MyProject2Editor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
1>Reflection code generated for MyProject2Editor in 8.1416845 seconds
1>Using Visual Studio 2017 14.13.26128 toolchain (e:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.13.26128) and Windows 10.0.16299.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Building 4 actions with 4 processes...
1>  [1/4] Module.ExodusImport.cpp
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/Tests/SkinMeshTest.cpp(53): error C2039: 'InvalidateDeriveDataCacheGUID': is not a member of 'USkeletalMesh'
1>  E:\New folder (5)\UE_4.23\Engine\Source\Runtime\Engine\Public\Animation/PreviewCollectionInterface.h(13): note: see declaration of 'USkeletalMesh'
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/Tests/SkinMeshTest.cpp(102): error C2065: 'FSkeletalMeshBuildSettings': undeclared identifier
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/Tests/SkinMeshTest.cpp(102): error C2146: syntax error: missing ';' before identifier 'buildSettings'
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/Tests/SkinMeshTest.cpp(102): error C2065: 'buildSettings': undeclared identifier
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/Tests/SkinMeshTest.cpp(103): error C2065: 'buildSettings': undeclared identifier
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/Tests/SkinMeshTest.cpp(103): error C2228: left of '.bRecomputeNormals' must have class/struct/union
1>  D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/Tests/SkinMeshTest.cpp(103): note: type is 'unknown-type'
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/Tests/SkinMeshTest.cpp(104): error C2065: 'buildSettings': undeclared identifier
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/Tests/SkinMeshTest.cpp(104): error C2228: left of '.bRecomputeTangents' must have class/struct/union
1>  D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/Tests/SkinMeshTest.cpp(104): note: type is 'unknown-type'
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/Tests/SkinMeshTest.cpp(117): error C2039: 'BuildSkeletalMesh': is not a member of 'IMeshBuilderModule'
1>  E:\New folder (5)\UE_4.23\Engine\Source\Developer\MeshBuilder\Public\IMeshBuilderModule.h(9): note: see declaration of 'IMeshBuilderModule'
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/UnrealUtilities.cpp(34): warning C4996: 'UStaticMesh::SourceModels': Please do not access this member directly; use UStaticMesh::GetSourceModel(LOD) or UStaticMesh::GetSourceModels(). Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>  E:\New folder (5)\UE_4.23\Engine\Source\Runtime\Engine\Classes\Engine/StaticMesh.h(577): note: see declaration of 'UStaticMesh::SourceModels'
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/UnrealUtilities.cpp(43): warning C4996: 'UStaticMesh::SourceModels': Please do not access this member directly; use UStaticMesh::GetSourceModel(LOD) or UStaticMesh::GetSourceModels(). Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>  E:\New folder (5)\UE_4.23\Engine\Source\Runtime\Engine\Classes\Engine/StaticMesh.h(577): note: see declaration of 'UStaticMesh::SourceModels'
1>D:/unreal projects/New folder/MyProject2/Plugins/ExodusImport/Source/ExodusImport/Private/UnrealUtilities.cpp(52): warning C4996: 'UStaticMesh::SourceModels': Please do not access this member directly; use UStaticMesh::GetSourceModel(LOD) or UStaticMesh::GetSourceModels(). Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
1>  E:\New folder (5)\UE_4.23\Engine\Source\Runtime\Engine\Classes\Engine/StaticMesh.h(577): note: see declaration of 'UStaticMesh::SourceModels'
1>e:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command ""E:\New folder (5)\UE_4.23\Engine\Build\BatchFiles\Build.bat" MyProject2Editor Win64 Development -Project="D:\unreal projects\New folder\MyProject2\MyProject2.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
1>Done building project "MyProject2.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========


I would very appreciate it if you could help me

**Comment by genemiller** [comment] 2021-01-19 22:46
Issue #21 is similar to Issue #47(UE4.25.4: Exodusimport "...module missing or built with a different engine version")

**Comment by genemiller** [comment] 2021-01-26 17:50
@Rombond This issue seems to be specifically related to running UE4 on MacOS.
I was able to work around this problem by installing UE4.23.4 on Windows10 on Parallels on  MacOS 10.15.
ExodusImport works perfectly on the SampleScene while running on UE4.23.4 on Windows10.
IMPORTANT NOTE: ExodusImport is still BROKEN in UE4.25.4 on **MacOS 10.15.**
I am CLOSING issue (#47) and leaving the original issue (#21) OPEN.

**Comment by NegInfinity** [comment] 2021-01-27 13:20
@MarshalScorpion This issue was related to a skeletal mesh test code which could not be compiled on unreal 4.23 or lower. The test has since been disabled for unreal 4.23.  I believe you contacted me via email regarding it and it was fixed.

**Comment by NegInfinity** [comment] 2021-01-27 13:26
I'm closing this issue due to original report being fairly old and no followup from vozer/Rombond for a year. In case someone experineces a similar issue, please open a new issue.

**Closed by NegInfinity** 2021-01-27 13:26 UTC

**Comment by chrisyan** [comment] 2021-03-24 16:16
> @Rombond Compiling manually means compiling it through C++ IDE. Without opening UNreal Engine. On Windows it would be compiling through Visual Studio, and on Mac Os that would likely be compiling through XCode. On windows system solution file can be generated by right clicking on *.upgroject and selecting "Generate Visual Studio Project files". Mac OS should have something similar.

Hi, i am using Ubuntu 18.04, and i get also the tip "try rebuilding from source manually", then I "make" the code in folder".../UnrealBlankProject", but I get 2 errors:

"/home/chris/exodus-demos/UnrealBlankProject1/Plugins/ExodusImport/Source/ExodusImport/Private/JsonObjects/getters.h:41:20: error: use of undeclared identifier 'jsonVal'
                                auto jsonObj = jsonVal->AsObject();
                                               ^
In file included from /home/chris/exodus-demos/UnrealBlankProject1/Plugins/ExodusImport/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/ExodusImport/Module.ExodusImport.cpp:3:
In file included from /home/chris/exodus-demos/UnrealBlankProject1/Plugins/ExodusImport/Source/ExodusImport/Private/builders/GeometryComponentBuilder.cpp:3:
In file included from /home/chris/exodus-demos/UnrealBlankProject1/Plugins/ExodusImport/Source/ExodusImport/Private/JsonImporter.h:7:
/home/chris/exodus-demos/UnrealBlankProject1/Plugins/ExodusImport/Source/ExodusImport/Private/MaterialBuilder.h:4:10: fatal error: 'MaterialBuilder/MaterialFingerprint.h' file not found
#include "MaterialBuilder/MaterialFingerprint.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
Makefile:950: recipe for target 'UE4Editor' failed
make: *** [UE4Editor] Error 5
"

so, would you mind giving me some tips to solve this error?  I appreciate!

**Comment by gawinwong** [comment] 2022-06-07 07:55
> > @Rombond Compiling manually means compiling it through C++ IDE. Without opening UNreal Engine. On Windows it would be compiling through Visual Studio, and on Mac Os that would likely be compiling through XCode. On windows system solution file can be generated by right clicking on *.upgroject and selecting "Generate Visual Studio Project files". Mac OS should have something similar.
> 
> Hi, i am using Ubuntu 18.04, and i get also the tip "try rebuilding from source manually", then I "make" the code in folder".../UnrealBlankProject", but I get 2 errors:
> 
> "/home/chris/exodus-demos/UnrealBlankProject1/Plugins/ExodusImport/Source/ExodusImport/Private/JsonObjects/getters.h:41:20: error: use of undeclared identifier 'jsonVal' auto jsonObj = jsonVal->AsObject(); ^ In file included from /home/chris/exodus-demos/UnrealBlankProject1/Plugins/ExodusImport/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/ExodusImport/Module.ExodusImport.cpp:3: In file included from /home/chris/exodus-demos/UnrealBlankProject1/Plugins/ExodusImport/Source/ExodusImport/Private/builders/GeometryComponentBuilder.cpp:3: In file included from /home/chris/exodus-demos/UnrealBlankProject1/Plugins/ExodusImport/Source/ExodusImport/Private/JsonImporter.h:7: /home/chris/exodus-demos/UnrealBlankProject1/Plugins/ExodusImport/Source/ExodusImport/Private/MaterialBuilder.h:4:10: fatal error: 'MaterialBuilder/MaterialFingerprint.h' file not found #include "MaterialBuilder/MaterialFingerprint.h" ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 2 errors generated. Makefile:950: recipe for target 'UE4Editor' failed make: *** [UE4Editor] Error 5 "
> 
> so, would you mind giving me some tips to solve this error? I appreciate!

Same problem, have you solved it?

**Comment by harryqk** [comment] 2022-06-17 02:13
same problem, on Mac
