### ISSUE TITLE
Cannot import into UE4.22

### ISSUE THREAD

**Issue by wrekklol** [NegInfinity/ProjectExodus#4] opened 2019-04-19 08:24 UTC
Exporting from Unity 2019.1.0f2, importing into UE4.22.
Assets are from Unity's asset store (POLYGON - Dungeons Pack).

[project.log](https://github.com/NegInfinity/ProjectExodus/files/3097504/project.log)

**Comment by NegInfinity** [comment] 2019-04-24 12:40
Hi.
I apologize for the slow reply, as somehow I missed the email notification.

Anyway.

I've removed Zipped exported files from public view because they technically still contain unity asset st ore assets, and those should not be publicly redistributed.

Regarding the issue you posted.
Please download the latest version of the code and see if it fixed the problem. Commit https://github.com/NegInfinity/ProjectExodus/commit/2abce6d0ac8eb2e31c46b57d18cd8436c24a7039 is supposed to deal with it.

If it still doesn't work, pleas let me know, what locale you're using - i.e. what is in your regional and language settings.

**Comment by wrekklol** [comment] 2019-04-24 13:01
Hello.

I just wanted to let you know that in 4.22(not sure if this is caused by
4.22 or something else like OS(I'm on Windows 10)) I had to change some
stuff in order to get the plugin running.

Line 78 of AnimationBuilder.cpp:
*animSeq->NumFrames = numFrames;*
to
*animSeq->SetRawNumberOfFrame(numFrames);*

Line 67 of ImportWorkData.h:
*:world(world_), editorMode(editorMode_), scene(scene_){*
to
*:scene(scene_), world(world_), editorMode(editorMode_){*

Line 20 of TerrainBuilder.cpp:

*:workData(workData_), importer(importer_), jsonGameObj(gameObj_),
jsonTerrain(jsonTerrain_), terrainData(terrainData_){*
to
*:importer(importer_), workData(workData_), jsonGameObj(gameObj_),
jsonTerrain(jsonTerrain_), terrainData(terrainData_){*



It seems to work now though, with the commit. But just in case, I'll post
my region settings below.

Region settings:

[image: image.png]

Den ons. 24. apr. 2019 kl. 14.40 skrev NegInfinity <notifications@github.com

**Comment by NegInfinity** [comment] 2019-04-24 13:06
The image is not linked properly, but if the problem has been fixed, there's no need for regioanl settings anymore.

The problem was caused by local handling on Unity side which pulled decimal separator from your OS settings, and your OS used "," for it.

As for the rest of the fixes... it looks like at the moment I'm still at 4.21.2 version of Unreal, I'll incorporate them into the build once I upgrade.

I'll be marking this as fixed for now, in case of other issues, either open another issue or github or contact me via email.

Have fun.

**Comment by wrekklol** [comment] 2019-04-24 13:22
The editor crashes upon saving an imported static mesh.
I don't have c++ symbols installed at the moment, so I can't give details
on exactly what's going on(couldn't find anything in the log either).

Den ons. 24. apr. 2019 kl. 15.07 skrev NegInfinity <notifications@github.com

**Comment by NegInfinity** [comment] 2019-04-24 14:33
> The editor crashes upon saving an imported static mesh.

Hi. Could you report this as a new issue? 

I'll try to look into it.

**Comment by NegInfinity** [comment] 2019-04-24 14:58
Alright. I've responded to the new issue, meanwhile I consider this one (unable to import) being fixed .

**Closed** 2019-04-24 14:58 UTC

**Comment by wrekklol** [comment] 2019-04-24 16:35
4.21.2 does not crash when saving the meshes.

Den ons. 24. apr. 2019 kl. 16.58 skrev NegInfinity <notifications@github.com
